version: '3.8'

services:
  frontend-service:
    build: ./frontend-service
    ports:
      - "8085:8085"
    environment:
      - SPRING_PROFILES_ACTIVE=prod
      - JWT_SECRET=${JWT_SECRET}
    networks:
      - enrollment-network
    depends_on:
      - api-gateway

  api-gateway:
    build: ./api-gateway
    ports:
      - "8080:8080"
    environment:
      - JWT_SECRET=${JWT_SECRET}
    networks:
      - enrollment-network
    depends_on:
      - auth-service

  auth-service:
    build: ./auth-service
    ports:
      - "8081:8081"
    environment:
      - SPRING_DATASOURCE_URL=jdbc:postgresql://enrollment-db:5432/enrollment_db?currentSchema=auth
      - SPRING_DATASOURCE_USERNAME=postgres
      - SPRING_DATASOURCE_PASSWORD=postgres
      - JWT_SECRET=${JWT_SECRET}
    networks:
      - enrollment-network
    depends_on:
      - enrollment-db

  enrollment-db:
    image: postgres:16
    ports:
      - "5432:5432"
    environment:
      - POSTGRES_DB=enrollment_db
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=postgres
    volumes:
      - enrollment-db-data:/var/lib/postgresql/data
      - ./init-db.sh:/docker-entrypoint-initdb.d/init-db.sh
    networks:
      - enrollment-network

networks:
  enrollment-network:
    driver: bridge

volumes:
  enrollment-db-data: 