server:
  port: 8080

spring:
  application:
    name: api-gateway
  cloud:
    gateway:
      routes:
        - id: auth-service
          uri: http://auth-service:8081
          predicates:
            - Path=/api/auth/**
          filters:
            - StripPrefix=1

        - id: course-service
          uri: http://course-service:8082
          predicates:
            - Path=/api/courses/**
          filters:
            - StripPrefix=1
            - name: JwtAuthenticationFilter

        - id: enrollment-service
          uri: http://enrollment-service:8083
          predicates:
            - Path=/api/enrollments/**
          filters:
            - StripPrefix=1
            - name: JwtAuthenticationFilter

        - id: grade-service
          uri: http://grade-service:8084
          predicates:
            - Path=/api/grades/**
          filters:
            - StripPrefix=1
            - name: JwtAuthenticationFilter

      globalcors:
        corsConfigurations:
          '[/**]':
            allowedOrigins: "http://localhost:8085"
            allowedMethods:
              - GET
              - POST
              - PUT
              - DELETE
            allowedHeaders:
              - '*'

jwt:
  secret: ${JWT_SECRET}
  expiration: 86400000 # 24 hours in milliseconds

management:
  endpoints:
    web:
      exposure:
        include: health,info,metrics 